name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.3'

      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          mkdir -p dist
          go build -ldflags="-s -w" -o dist/gembot_linux_amd64 ./cmd/gembot/...

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: gembot-linux-x86_64
          path: dist/gembot_linux_amd64
          if-no-files-found: error
